FROM node:18-alpine as builder

WORKDIR /app

COPY apps/nextjs-frontend/package*.json ./

RUN npm ci

COPY apps/nextjs-frontend .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

RUN npm ci --only=production

EXPOSE 3000

CMD ["npm", "start"]
